---
abstract: 'KING OF CMS'
author:
  - 'Devin Austin <dhoss@cpan.org>'
build_requires:
  Test::DBIx::Class: 0.28
  Test::More: 0.88
  Test::WWW::Mechanize::PSGI: 0.35
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Grimlock
requires:
  Bread::Board: 0
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Controller::REST: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::I18N: 0
  Catalyst::Plugin::MessageStack: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::DBIC: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.90007
  Catalyst::View::JSON: 0
  Catalyst::View::TT: 0
  Config::General: 0
  DBICx::MaterializedPath: 0.03
  DBIx::Class: 0.08196
  DBIx::Class::Candy: 0
  DBIx::Class::EncodedColumn::Crypt::Eksblowfish::Bcrypt: 0
  DBIx::Class::Helper::Row::ToJSON: 0
  Data::Manager: 0
  Email::Sender::Simple: 0
  Moose: 0
  Template::Plugin::Filter::String::Truncate: 0.02
  Text::Password::Pronounceable: 0
  namespace::autoclean: 0
resources:
  repository: git://github.com/dhoss/Grimlock.git
version: 0.02
